server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    #max-threads: 1000
    max-connections: 20000
  #connection-timeout: 5000

spring:
  mvc:
    static-path-pattern: /**
  resources:
    add-mappings: true
    static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/yelp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      #dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true